### ISSUE TITLE
Scrolling up seems to be slower then scrolling down

### ISSUE THREAD

**Issue by cmahnke** [entrope/linux-magicmouse#2] opened 2010-02-03 18:54 UTC
The scrolling behavior of the mouse doesn't seem to be balanced in both directions(up / down).

**Comment by bogdanroman** [comment] 2010-02-05 07:55
I noticed the same behavior; the problem seems to appear because after scrolling up once, when you place your finger closer to the apple logo to scroll again, it will scroll downwards a bit.

**Comment by entrope** [comment] 2010-02-06 17:33
This should be fixed in commit 3306fac.  (The cause was a premature and invalid optimization: I had a right shift to divide the touch motion down to a scroll step, but negative numbers shift towards -1 rather than going to 0.)

**Closed as completed by entrope** 2010-02-06 17:33 UTC
